### ISSUE TITLE
Feature Request - Programatically show/hide tooltip via context?

### ISSUE THREAD

**Issue by DurgeshSawantWYLD** [stassop/flutter_animated_tooltip#3]
Show a tooltip on initState when a condition is satisfied

For ex.
initState > new user > show New User tooltip

Currently the tooltip is only visible onTap..

If there could be a way in which we could show/hide the tooltip programmatically via context..

**Comment by stassop** [comment]
You can use the `delay` prop to show the tooltip automatically after a duration of time. Hope it helps.

**Comment by DurgeshSawantWYLD** [comment]
Understood Thanks!
